add instance name

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -9,26 +9,22 @@ on:
 jobs:
   check-image-and-deploy:
     runs-on: ubuntu-latest
-
     steps:
-      # Step 1: Checkout code
       - name: Checkout Repository
-        uses: actions/checkout@v3    
-        
-      # Step 2: Check if Docker Image Exists
+        uses: actions/checkout@v3
+
       - name: Check if Docker Image Exists
         id: check_image
         run: |
-          REPOSITORY="${{ secrets.DOCKERHUB_USERNAME }}/calc_workflows"  # Replace with your DockerHub repository name
+          REPOSITORY="${{ secrets.DOCKERHUB_USERNAME }}/calc_workflows"
           TAG="latest"
           RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" https://hub.docker.com/v2/repositories/${REPOSITORY}/tags/${TAG}/)
           if [ "$RESPONSE" -ne 200 ]; then
-              echo "Docker image not found. Exiting workflow."
-              exit 1
+            echo "Docker image not found. Exiting workflow."
+            exit 1
           fi
           echo "Docker image exists. Proceeding to deployment."
 
-      # Step 3: Set AWS Credentials in Environment Variables
       - name: Set AWS Credentials
         if: ${{ steps.check_image.outcome == 'success' }}
         env:
@@ -38,7 +34,6 @@ jobs:
           AWS_REGION: ${{ secrets.AWS_REGION }}
         run: echo "AWS credentials set."
 
-      # Step 4: Create EC2 Instance and Deploy the Application
       - name: Create EC2 Instance and Deploy the Application
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -46,24 +41,26 @@ jobs:
           AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
           AWS_REGION: ${{ secrets.AWS_REGION }}
         run: |
-          # Define instance details
+          # Define instance details with tags
           INSTANCE_ID=$(aws ec2 run-instances \
             --image-id ami-06b21ccaeff8cd686 \
             --instance-type t2.micro \
             --key-name ${{ secrets.AWS_KEYPAIR_NAME }} \
             --security-group-ids ${{ secrets.AWS_SG_ID }} \
             --user-data file://user-data.sh \
+            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=Calculator-App},{Key=Environment,Value=Production}]' \
             --query 'Instances[0].InstanceId' \
             --output text)
-
+          
           echo "Instance ID: $INSTANCE_ID"
-
+          
           # Wait for the instance to be running
           aws ec2 wait instance-running --instance-ids $INSTANCE_ID
-
+          
           # Output the instance public DNS
           INSTANCE_PUBLIC_DNS=$(aws ec2 describe-instances \
             --instance-ids $INSTANCE_ID \
             --query 'Reservations[0].Instances[0].PublicDnsName' \
             --output text)
+          
           echo "Instance Public DNS: $INSTANCE_PUBLIC_DNS"
